baseURL = "/"
disqusShortname = ""
languageCode = "en-au"
paginate = "5"
summaryLength = "10"
theme = "northendlab-light"
title = "The SCCM blog of Quentin Escott"
[menu]
footer = []
main = []
[outputs]
home = []
[params]
author = "Themefisher"
contact_form_action = "#"
copyright = "&copy; 2022 Escott Defence Services Pty Ltd"
description = "The SCCM blog of Quentin Escott"
google_analitycs_id = ""
google_tag_manager = ""
home = ""
logo = "images/cmlogo.png"
[params.banner]
bgImage = ""
image = ""
title = "The SCCM blog of Quentin Escott."
[params.cta]
description = ""
enable = false
image = ""
title = ""
[params.cta.button]
enable = false
label = ""
link = ""
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[params.preloader]
enable = false
preloader = ""
[params.search]
enable = true
[[params.social]]
icon = "ti-linkedin"
link = "https://www.linkedin.com/in/quentinescott/"
